kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cinemaabyss

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
      - containerPort: 32080
        hostPort: 32080

    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"

    extraMounts:
      - hostPath: /var/lib/kind
        containerPath: /var/lib/kind
